### ISSUE TITLE
Qnap app loses connection with NAS

### ISSUE THREAD

**Issue by mcrbrauers** [RonnyWinkler/homey.qnap#2]
The Qnap app was easy to install, but every time the app lose connection with the NAS. The only thing that will help is to restart the app or reconfigurate the app. Then it w work for about 2hours. And then I have to do the same action again. How do I fix this?

**Comment by RonnyWinkler** [comment]
The app is connecting to the NAS on every period, which is set in device settings. If teh app could not connect (no response, service not available), the device gets the exclamation mark and in device details, a error text is shown. Often this is caused by a high server load. With the next retry, the device will normally get available again showing the NAS data after a successful connection.

In your case it seems that the app itself got stopped or is crashed. Can you see such an error message in app details in the mobile app? I saw some error log caused by invalid or missing NAS data which could cause an app crash. Thsi is fixed in th enew version (1.0.11) and there haven't been app cashes since 23.09.2022.

Please check if you have the latest version installed. Activate automatic update to get the latest version.

If you have the new version installed, please describe the error:
- make a screenshot from device details including the error message
- check the app details if th eapp cot crashed
- create a diagnostic report and send me the ID (possible as PM in Homey community). I will check if I can see some details/error logs.

Thanks and kind regards
Ronny

**Comment by mcrbrauers** [comment]
Thanks for your advice and explaination.

 

I’ll check the app version and go have a look at my NAS and router settings. 

I hope this wil fix the problems. 

If not, I let you know and send you the error message. 


Thanks!!

 

Best regards,

 

Marcel Brauers

 

 

Van: RonnyWinkler ***@***.***> 
Verzonden: maandag 26 september 2022 21:42
Aan: RonnyWinkler/homey.qnap ***@***.***>
CC: mcrbrauers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [RonnyWinkler/homey.qnap] Qnap app loses connection with NAS (Issue #2)

 

The app is connecting to the NAS on every period, which is set in device settings. If teh app could not connect (no response, service not available), the device gets the exclamation mark and in device details, a error text is shown. Often this is caused by a high server load. With the next retry, the device will normally get available again showing the NAS data after a successful connection.

In your case it seems that the app itself got stopped or is crashed. Can you see such an error message in app details in the mobile app? I saw some error log caused by invalid or missing NAS data which could cause an app crash. Thsi is fixed in th enew version (1.0.11) and there haven't been app cashes since 23.09.2022.

Please check if you have the latest version installed. Activate automatic update to get the latest version.

If you have the new version installed, please describe the error:

*	make a screenshot from device details including the error message
*	check the app details if th eapp cot crashed
*	create a diagnostic report and send me the ID (possible as PM in Homey community). I will check if I can see some details/error logs.

Thanks and kind regards
Ronny

**Comment by RonnyWinkler** [comment]
Hello @mcrbrauers 
have you found the reason as you closed this issue? If not just reopen or leave a comment. Thanks.
